// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKpclV09GJsQwRnCmdQZdJA9YxH28NPIU',
    appId: '1:104829179491:web:fd3676f46960f7dad50a56',
    messagingSenderId: '104829179491',
    projectId: 'noteappclone',
    authDomain: 'noteappclone.firebaseapp.com',
    storageBucket: 'noteappclone.appspot.com',
    measurementId: 'G-XB9RYHKSKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxjZWCsCTxQjhvmeEhELJ-phVxk-0gOM',
    appId: '1:104829179491:android:d61a6cfab04c60c6d50a56',
    messagingSenderId: '104829179491',
    projectId: 'noteappclone',
    storageBucket: 'noteappclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxZyvnnVRdb07p1atAuzV6HeZIrys2FzU',
    appId: '1:104829179491:ios:5af0209e0d0b5dd9d50a56',
    messagingSenderId: '104829179491',
    projectId: 'noteappclone',
    storageBucket: 'noteappclone.appspot.com',
    iosBundleId: 'com.example.googleNotesAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxZyvnnVRdb07p1atAuzV6HeZIrys2FzU',
    appId: '1:104829179491:ios:bb2e30f199ed5ffcd50a56',
    messagingSenderId: '104829179491',
    projectId: 'noteappclone',
    storageBucket: 'noteappclone.appspot.com',
    iosBundleId: 'com.example.googleNotesAppClone.RunnerTests',
  );
}
